"""Canonical Knowledge Library retrieval API."""

from __future__ import annotations

from .legacy import (
    CanonicalRetriever,
    ExactCanonicalRetriever,
    FIELD_WEIGHTS,
    FutureHybridRetriever,
    FutureSemanticRetriever,
    MAX_FIELD_WEIGHT,
    MATCH_TYPE_PRIORITY,
    RetrievalResult,
    canonical_search_terms as legacy_canonical_search_terms,
    category_bonus,
    collect_field_search_terms,
    exact_match_bonus,
    field_search_terms,
    fuzzy_match_bonus,
    governance_bonus,
    infer_query_categories,
    phrase_match_bonus,
    query_search_terms,
    score_keyword_result,
    score_text_match,
    sort_retrieval_results,
)
from .indexer import CKLIndex, IndexedCKLEntry, clear_index_cache, inventory_signature, load_index, refresh_index
from .models import CKLIndexStats, CKLSearchResponse, CKLSearchResult, QueryAnalysis, ScoreSignal
from .ranker import (
    ALIAS_MATCH_WEIGHT,
    CATEGORY_MATCH_WEIGHT,
    FACT_MATCH_WEIGHT,
    KEYWORD_MATCH_WEIGHT,
    PHRASE_MATCH_WEIGHT,
    RELATED_MATCH_WEIGHT,
    SCRIPTURE_MATCH_WEIGHT,
    THEME_MATCH_WEIGHT,
    TITLE_MATCH_WEIGHT,
    score_indexed_candidates,
    score_indexed_entry,
)
from .service import CKLRetrievalService, load_service, search
from .tokenizer import (
    PROTECTED_PHRASES,
    STOP_WORDS,
    analyze_query,
    canonical_search_terms,
    detect_scripture_references,
    extract_phrases,
    extract_terms,
    guess_intent,
    normalize_query,
)

__all__ = [
    "CanonicalRetriever",
    "ExactCanonicalRetriever",
    "FutureSemanticRetriever",
    "FutureHybridRetriever",
    "RetrievalResult",
    "FIELD_WEIGHTS",
    "MAX_FIELD_WEIGHT",
    "MATCH_TYPE_PRIORITY",
    "canonical_search_terms",
    "legacy_canonical_search_terms",
    "category_bonus",
    "collect_field_search_terms",
    "exact_match_bonus",
    "field_search_terms",
    "fuzzy_match_bonus",
    "governance_bonus",
    "infer_query_categories",
    "phrase_match_bonus",
    "query_search_terms",
    "score_keyword_result",
    "score_text_match",
    "sort_retrieval_results",
    "CKLIndex",
    "IndexedCKLEntry",
    "CKLIndexStats",
    "CKLSearchResponse",
    "CKLSearchResult",
    "QueryAnalysis",
    "ScoreSignal",
    "CKLRetrievalService",
    "load_index",
    "load_service",
    "refresh_index",
    "clear_index_cache",
    "inventory_signature",
    "search",
    "TITLE_MATCH_WEIGHT",
    "ALIAS_MATCH_WEIGHT",
    "SCRIPTURE_MATCH_WEIGHT",
    "PHRASE_MATCH_WEIGHT",
    "KEYWORD_MATCH_WEIGHT",
    "THEME_MATCH_WEIGHT",
    "FACT_MATCH_WEIGHT",
    "RELATED_MATCH_WEIGHT",
    "CATEGORY_MATCH_WEIGHT",
    "score_indexed_entry",
    "score_indexed_candidates",
    "PROTECTED_PHRASES",
    "STOP_WORDS",
    "analyze_query",
    "detect_scripture_references",
    "extract_phrases",
    "extract_terms",
    "guess_intent",
    "normalize_query",
]
