"""Canonical Knowledge Library public API."""

from __future__ import annotations

from .context_builder import CanonicalContextBuilder
from .loader import CanonicalLibrary
from .normalization import normalize_alias, normalize_id, normalize_text, tokenize_query
from .public_cache import (
    DEFAULT_PUBLIC_CACHE_PATH,
    JsonPublicAnswerCache,
    NullPublicAnswerCache,
    PublicAnswerCache,
    PublicCacheEntry,
    load_framework_version,
    load_framework_version_fingerprint,
    normalize_public_question,
    public_cache_key,
)
from .retrieval import (
    CanonicalRetriever,
    ExactCanonicalRetriever,
    FutureHybridRetriever,
    FutureSemanticRetriever,
    RetrievalResult,
)
from .schema import (
    CATEGORY_FOLDERS,
    CONFIDENCE_VALUES,
    CONTENT_STATUS_VALUES,
    DEFAULT_GOVERNANCE_METADATA,
    REVIEW_STATUS_VALUES,
    CanonicalScriptureReference,
    CanonicalSource,
    SUPPORTED_CATEGORIES,
    CanonicalRelationship,
    CanonicalObject,
    CanonicalValidationError,
    normalize_sources_field,
    validate_aliases,
    validate_category_type,
    validate_approved_content_requirements,
    validate_field_types,
    validate_governance_metadata,
    validate_library,
    validate_object,
    validate_related_object_entry,
    validate_related_objects_field,
    validate_scripture_reference_entry,
    validate_scripture_references_field,
    validate_source_entry,
    validate_required_fields,
)

__version__ = load_framework_version()

__all__ = [
    "__version__",
    "CanonicalLibrary",
    "CanonicalContextBuilder",
    "CanonicalObject",
    "CanonicalValidationError",
    "RetrievalResult",
    "CanonicalRetriever",
    "ExactCanonicalRetriever",
    "FutureSemanticRetriever",
    "FutureHybridRetriever",
    "PublicCacheEntry",
    "PublicAnswerCache",
    "JsonPublicAnswerCache",
    "NullPublicAnswerCache",
    "DEFAULT_PUBLIC_CACHE_PATH",
    "load_framework_version",
    "load_framework_version_fingerprint",
    "normalize_public_question",
    "public_cache_key",
    "normalize_text",
    "normalize_id",
    "normalize_alias",
    "tokenize_query",
    "SUPPORTED_CATEGORIES",
    "CATEGORY_FOLDERS",
    "CONTENT_STATUS_VALUES",
    "REVIEW_STATUS_VALUES",
    "CONFIDENCE_VALUES",
    "DEFAULT_GOVERNANCE_METADATA",
    "CanonicalRelationship",
    "CanonicalScriptureReference",
    "CanonicalSource",
    "validate_object",
    "validate_library",
    "validate_required_fields",
    "validate_field_types",
    "validate_category_type",
    "validate_aliases",
    "validate_governance_metadata",
    "validate_approved_content_requirements",
    "validate_related_object_entry",
    "validate_related_objects_field",
    "validate_scripture_reference_entry",
    "validate_scripture_references_field",
    "validate_source_entry",
    "normalize_sources_field",
]
