"""Curated cross-period archaeology expansion.

This is deliberately data, not a second archaeology system.  The records are
merged into :mod:`archaeology_content` and use its existing site, item,
Scripture-link, media, map, and rights-aware import paths.
"""

from __future__ import annotations

from typing import Any


def _site(
    id: str, name: str, site_type: str, period: str, latitude: float,
    longitude: float, modern_location: str, region: str, description: str,
    source_name: str, source_url: str, *, periods: list[str], notes: str = "",
) -> dict[str, Any]:
    return {
        "id": id, "name": name, "site_type": site_type, "period": period,
        "periods": periods, "latitude": latitude, "longitude": longitude,
        "modern_location": modern_location, "ancient_region": region,
        "description": description, "confidence": "strong", "confidence_rank": 5,
        "source_name": source_name, "source_url": source_url,
        "license": "Institutional source", "notes": notes or "Site-center coordinate for map display.",
    }


def _item(
    id: str, site_id: str, name: str, item_type: str, period: str,
    relationship: str, why: str, caution: str, description: str, discovery: str,
    physical: str, summary: str, relevance: str, date_display: str,
    dating: str, scholarly: str, location: str, source_name: str, source_url: str,
    *, periods: list[str], dispute: str = "not_disputed", confidence: str = "strong",
) -> dict[str, Any]:
    return {
        "id": id, "site_id": site_id, "name": name, "item_type": item_type,
        "period": period, "periods": periods, "relationship": relationship,
        "why_it_matters": why, "bhf_caution": caution, "confidence": confidence,
        "confidence_rank": 5 if confidence == "strong" else 4,
        "source_name": source_name, "source_url": source_url,
        "license": "Institutional source", "notes": "Reviewed institutional or academic source; media is added only after separate rights review.",
        "evidence_details": {
            "description": description, "discovery_context": discovery,
            "date_display": date_display, "dating_basis": dating,
            "physical_description": physical, "evidence_summary": summary,
            "biblical_relevance": relevance, "scholarly_context": scholarly,
            "interpretive_caution": caution, "current_location": location,
            "dispute_status": dispute,
        },
    }


ARCHAEOLOGY_SITES: list[dict[str, Any]] = [
    _site("mari", "Mari (Tell Hariri)", "Bronze Age palace city", "Middle and Late Bronze Age", 34.55, 40.89, "Deir ez-Zor Governorate, Syria", "Middle Euphrates", "A royal city whose palace archive documents diplomacy, administration, and travel in the early second millennium BCE.", "Louvre Museum", "https://www.louvre.fr/en/explore/the-palace/the-palace-of-mari", periods=["Broad / uncertain period"]),
    _site("ebla", "Ebla (Tell Mardikh)", "Bronze Age urban archive site", "Early and Middle Bronze Age", 35.80, 36.80, "Idlib Governorate, Syria", "Northern Levant", "A major Syrian city where palace archives preserve third-millennium administration and culture.", "Sapienza University of Rome", "https://ebla-archive-archivio-ebraico.saras.uniroma1.it/", periods=["Broad / uncertain period"]),
    _site("ugarit", "Ugarit (Ras Shamra)", "Late Bronze Age port city", "Late Bronze Age", 35.60, 35.78, "Latakia Governorate, Syria", "Northern Levant", "A coastal city with alphabetic and cuneiform archives important for Levantine religion and literature.", "Louvre Museum", "https://www.louvre.fr/en/explore/the-palace/ugarit-a-cosmopolitan-city", periods=["Broad / uncertain period"]),
    _site("amarna", "Akhetaten (Amarna)", "New Kingdom Egyptian capital", "New Kingdom Egypt", 27.65, 30.90, "Minya Governorate, Egypt", "Middle Egypt", "Akhenaten's short-lived capital, which produced an international diplomatic archive.", "Amarna Project", "https://www.amarnaproject.com/", periods=["Broad / uncertain period"]),
    _site("beni-hasan", "Beni Hasan", "Middle Kingdom tomb cemetery", "Middle Kingdom Egypt", 27.93, 30.88, "Minya Governorate, Egypt", "Middle Egypt", "A cemetery whose decorated tombs preserve visual evidence for Egyptian elite life and foreign visitors.", "Metropolitan Museum of Art", "https://www.metmuseum.org/art/collection/search/544858", periods=["Broad / uncertain period"]),
    _site("shechem", "Shechem (Tell Balata)", "fortified tell", "Middle Bronze Age to Roman period", 32.21, 35.28, "Nablus, West Bank", "Central Highlands", "An important highland city with Middle Bronze fortifications and later occupation.", "UNESCO World Heritage Centre", "https://whc.unesco.org/en/tentativelists/5708/", periods=["Broad / uncertain period", "Divided Kingdom"]),
    _site("avaris", "Avaris (Tell el-Dab'a)", "Egyptian Delta settlement", "Middle Bronze to New Kingdom Egypt", 30.79, 31.82, "Sharqia Governorate, Egypt", "Eastern Nile Delta", "A long-lived Delta settlement with western Asiatic communities and later New Kingdom royal activity.", "Austrian Archaeological Institute", "https://www.oeaw.ac.at/oeai/research/egypt-and-levant/tell-el-daba", periods=["Broad / uncertain period"]),
    _site("pi-rameses", "Pi-Ramesses (Qantir)", "New Kingdom royal capital", "New Kingdom Egypt", 30.79, 31.84, "Sharqia Governorate, Egypt", "Eastern Nile Delta", "A Ramesside capital whose workshops and buildings illuminate New Kingdom state logistics.", "Roemer- und Pelizaeus-Museum", "https://www.rpmuseum.de/forschung/projekte/qantir-piramesse.html", periods=["Broad / uncertain period"]),
    _site("timnah", "Timnah (Tel Batash)", "Iron Age border town", "Late Bronze and Iron Age", 31.71, 34.96, "Elah Valley, Israel", "Shephelah", "A border-region tell with Late Bronze and Iron Age settlement phases.", "Tel Aviv University", "https://english.tau.ac.il/news/timnah", periods=["Divided Kingdom"]),
    _site("ekron", "Ekron (Tel Miqne)", "Philistine city", "Iron Age", 31.77, 34.84, "Southern Coastal Plain, Israel", "Philistia", "One of the major Philistine cities, extensively excavated with industrial and cultic remains.", "Israel Antiquities Authority", "https://www.antiquities.org.il/", periods=["Divided Kingdom", "Assyrian period"]),
    _site("tel-qasile", "Tel Qasile", "Philistine coastal settlement", "Iron Age", 32.10, 34.79, "Tel Aviv, Israel", "Philistia", "A Philistine settlement with successive temple buildings near the Yarkon River.", "Israel Museum", "https://www.imj.org.il/en/collections/", periods=["Divided Kingdom"]),
    _site("gezer", "Gezer (Tel Gezer)", "fortified tell", "Bronze Age to Hellenistic period", 31.88, 34.92, "Central Israel", "Shephelah", "A strategic tell with a long sequence of fortifications, public buildings, and inscriptions.", "Tandy Institute for Archaeology", "https://www.neworleansbaptist.org/gezer/", periods=["Broad / uncertain period", "Divided Kingdom"]),
    _site("khirbet-qeiyafa", "Khirbet Qeiyafa", "fortified Iron Age site", "Iron Age IIA", 31.70, 34.96, "Elah Valley, Israel", "Shephelah", "A short-lived fortified site overlooking the Elah Valley, with an ostracon and distinctive urban plan.", "Hebrew University of Jerusalem", "https://qeiyafa.huji.ac.il/", periods=["Divided Kingdom"]),
    _site("kuntillet-ajrud", "Kuntillet Ajrud", "desert way-station", "Iron Age II", 30.20, 34.42, "Northeastern Sinai, Egypt", "Southern Levant", "An Iron Age way-station with inscriptions and drawings on plaster and pottery.", "Israel Museum", "https://www.imj.org.il/en/collections/", periods=["Divided Kingdom"]),
    _site("corinth", "Corinth", "Greek and Roman city", "Hellenistic to Roman period", 37.91, 22.88, "Ancient Corinth, Greece", "Achaia", "A major Roman colony with forum, civic buildings, inscriptions, and a harbor network.", "American School of Classical Studies at Athens", "https://www.ascsa.edu.gr/excavations/research/corinth", periods=["Hellenistic period", "NT / Roman period"]),
    _site("ephesus", "Ephesus", "Hellenistic and Roman city", "Hellenistic to Roman period", 37.94, 27.34, "Selçuk, Türkiye", "Asia Minor", "A major harbor city with civic, commercial, religious, and imperial architecture.", "Austrian Archaeological Institute", "https://www.oeaw.ac.at/oeai/research/ephesos", periods=["Hellenistic period", "NT / Roman period"]),
    _site("philippi", "Philippi", "Macedonian and Roman colony", "Hellenistic to Roman period", 41.01, 24.29, "Krinides, Greece", "Macedonia", "A Roman colony with forum, public inscriptions, roads, and early Christian remains.", "Greek Ministry of Culture", "https://odysseus.culture.gr/h/3/eh351.jsp?obj_id=18848", periods=["Hellenistic period", "NT / Roman period"]),
    _site("smyrna", "Smyrna", "Hellenistic and Roman city", "Hellenistic to Roman period", 38.42, 27.14, "İzmir, Türkiye", "Asia Minor", "A major Aegean city whose agora and inscriptions illuminate Roman civic life.", "İzmir Archaeology Museum", "https://muze.gov.tr/muze-detay?SectionId=IZM01&DistId=MRK", periods=["Hellenistic period", "NT / Roman period"]),
    _site("pergamum", "Pergamum", "Hellenistic and Roman acropolis city", "Hellenistic to Roman period", 39.13, 27.18, "Bergama, Türkiye", "Asia Minor", "A royal and Roman city with a monumental acropolis, sanctuaries, and imperial cult evidence.", "German Archaeological Institute", "https://www.dainst.org/en/research/projects/nosl/2225", periods=["Hellenistic period", "NT / Roman period"]),
    _site("thyatira", "Thyatira", "Roman commercial city", "Roman period", 38.92, 27.84, "Akhisar, Türkiye", "Asia Minor", "A Roman city known for trade guilds, inscriptions, and later Christian occupation.", "Türkiye Ministry of Culture and Tourism", "https://whc.unesco.org/en/tentativelists/6243/", periods=["NT / Roman period"]),
    _site("sardis", "Sardis", "Lydian, Hellenistic, and Roman city", "Hellenistic to Roman period", 38.49, 28.04, "Sart, Türkiye", "Lydia", "A wealthy urban center with a synagogue, bath-gymnasium, temple, and civic architecture.", "Harvard Art Museums / Sardis Expedition", "https://sardisexpedition.org/", periods=["Hellenistic period", "NT / Roman period"]),
    _site("philadelphia-lydia", "Philadelphia (Lydia)", "Roman city", "Roman period", 38.35, 28.52, "Alaşehir, Türkiye", "Lydia", "An inland Lydian city with Roman-era remains and later Byzantine fortifications.", "Türkiye Ministry of Culture and Tourism", "https://whc.unesco.org/en/tentativelists/6243/", periods=["NT / Roman period"]),
    _site("laodicea", "Laodicea on the Lycus", "Hellenistic and Roman city", "Hellenistic to Roman period", 37.83, 29.11, "Denizli, Türkiye", "Phrygia", "A prosperous city with water infrastructure, streets, theaters, and public buildings.", "Laodicea Excavations", "https://laodikeia.pau.edu.tr/", periods=["Hellenistic period", "NT / Roman period"]),
    _site("nazareth", "Nazareth", "early Roman-period village", "Hellenistic to Roman period", 32.70, 35.30, "Nazareth, Israel", "Galilee", "A Galilean village with early Roman-period domestic and burial evidence.", "Israel Antiquities Authority", "https://www.antiquities.org.il/", periods=["Hellenistic period", "NT / Roman period"]),
    _site("magdala", "Magdala", "early Roman lakeside town", "Hellenistic to Roman period", 32.83, 35.51, "Migdal, Israel", "Galilee", "A lakeside town with a first-century synagogue, streets, ritual baths, and fish-processing installations.", "Israel Antiquities Authority", "https://www.antiquities.org.il/", periods=["Hellenistic period", "NT / Roman period"]),
    _site("bethsaida", "Bethsaida candidates", "Galilean lakeshore settlement area", "Iron Age to Roman period", 32.91, 35.62, "Northern Sea of Galilee, Israel", "Galilee / Golan", "The et-Tell and el-Araj excavations are competing candidates for the Bethsaida of the Gospels.", "Kinneret Institute for Galilean Archaeology", "https://www.kinneret.ac.il/en/kinneret-institute-for-galilean-archaeology/", periods=["Divided Kingdom", "NT / Roman period"], notes="Map coordinate is a regional study center, not a claim that one candidate is certain."),
    _site("galilee-boat-site", "Gennesaret boat findspot", "lakeshore findspot", "early Roman period", 32.85, 35.53, "Northwest Sea of Galilee, Israel", "Galilee", "The 1986 discovery location of a first-century fishing boat preserved in lake sediments.", "Yigal Allon Centre", "https://yigal-allon-centre.org.il/", periods=["NT / Roman period"]),
]


ARCHAEOLOGY_ITEMS: list[dict[str, Any]] = [
    _item("mari-tablets", "mari", "Mari Palace Tablets", "cuneiform administrative and diplomatic archive", "early 2nd millennium BCE", "comparative Near Eastern administration", "They make the diplomacy, travel, religion, and household administration of the Middle Bronze Near East materially concrete.", "The Mari archive is comparative evidence and does not document Abraham, the patriarchs, or Genesis events.", "More than 20,000 tablets from the royal palace archive at Mari.", "French excavations beginning in 1933 uncovered the palace archive in room groups and debris deposits.", "Clay tablets written mainly in Akkadian cuneiform.", "The archive records royal correspondence, provisioning, cult, diplomacy, and movement along the Euphrates.", "It gives cultural context for the kind of West Semitic and Mesopotamian world presupposed by Genesis 12–24.", "18th century BCE", "Palaeography, archive context, and historical synchronisms", "The archive is secure; using individual Mari customs to reconstruct a specific patriarchal practice is methodologically contested.", "Louvre Museum and Syrian collections", "Louvre Museum", "https://www.louvre.fr/en/explore/the-palace/the-palace-of-mari", periods=["Broad / uncertain period"], dispute="interpretation_disputed"),
    _item("ebla-archives", "ebla", "Ebla Palace G Archives", "cuneiform palace archive", "mid-3rd millennium BCE", "comparative Syrian urban context", "They document a complex Syrian court, economy, and scribal culture long before the biblical narratives were written.", "Place-name similarities or broad cultural parallels do not establish direct biblical correlations.", "Thousands of tablets and fragments from the Palace G archive at Ebla.", "Italian excavations found tablets collapsed on shelves in the palace archive rooms in the 1970s.", "Clay tablets in Sumerian and Eblaite, including lexical, administrative, and diplomatic texts.", "The archive is primary evidence for literacy and state administration in Early Bronze Syria.", "It supplies broad comparative background for Genesis's northern Syrian and Mesopotamian horizon without proving patriarchal traditions.", "c. 2400–2250 BCE", "Stratigraphy, script, and archive context", "The archive's significance is established; early popular claims about direct biblical names are not accepted as reliable evidence.", "Idlib Museum collections and excavation archives", "Sapienza University of Rome", "https://ebla-archive-archivio-ebraico.saras.uniroma1.it/", periods=["Broad / uncertain period"], dispute="interpretation_disputed"),
    _item("ugarit-ras-shamra", "ugarit", "Ugarit / Ras Shamra Archaeological Site", "Late Bronze urban and archive context", "Late Bronze Age", "Canaanite religious and literary context", "The city and its archives clarify the material setting of a coastal Levantine polity.", "Ugaritic texts are not Israelite texts and should not be used to flatten important religious and chronological differences.", "A Late Bronze port city with palaces, temples, houses, and multiple archives.", "Excavations begun in 1929 after a tomb discovery and exposed archives in palace, temple, and private contexts.", "Urban ruins with alphabetic and syllabic cuneiform tablets, cultic installations, and imported goods.", "Ugarit documents a literate, interconnected Levantine world shortly before the Iron Age.", "It provides comparative context for Canaanite religion and poetry relevant to passages confronting Baal worship, including Judges 2.", "c. 1550–1200 BCE", "Stratigraphy, imported wares, and textual chronology", "The site is securely dated; proposed direct borrowing between specific Ugaritic and biblical texts remains debated.", "Damascus and Latakia museum collections; Ras Shamra site", "Louvre Museum", "https://www.louvre.fr/en/explore/the-palace/ugarit-a-cosmopolitan-city", periods=["Broad / uncertain period"], dispute="interpretation_disputed"),
    _item("ugaritic-baal-cycle", "ugarit", "Ugaritic Baal Cycle Tablets", "alphabetic cuneiform literary tablets", "Late Bronze Age", "comparative religious literature", "The tablets preserve mythic poetry about Baal, Mot, and other deities known in the wider Levant.", "The texts provide comparison, not a direct explanation of every biblical use of Baal language.", "A group of alphabetic cuneiform tablets from Ugarit's archives.", "Recovered in the acropolis area during twentieth-century excavations at Ras Shamra.", "Clay tablets written in the Ugaritic alphabetic cuneiform script.", "They are a major primary source for Late Bronze West Semitic religious vocabulary and mythology.", "They contextualize biblical polemic against Baal in passages such as 1 Kings 18 while remaining a distinct corpus.", "13th century BCE", "Archaeological context and palaeography", "Translations and literary reconstruction are widely studied; direct literary dependence with biblical texts is disputed.", "Louvre Museum, Paris", "Louvre Museum", "https://collections.louvre.fr/en/ark:/53355/cl010141827", periods=["Broad / uncertain period"], dispute="interpretation_disputed"),
    _item("amarna-letters", "amarna", "Amarna Letters", "international diplomatic archive", "Late Bronze Age", "Canaanite city-state political context", "The letters show Egyptian imperial administration and competing Canaanite city rulers.", "They do not narrate the Exodus, conquest, or identify every group sometimes compared with biblical terms.", "A corpus of diplomatic tablets exchanged among Egypt, Levantine rulers, and other Great Powers.", "Found in 1887 at Akhetaten and subsequently excavated in the records office area.", "Akkadian cuneiform tablets, often written by non-native Akkadian scribes.", "They provide direct evidence for Late Bronze political fragmentation, tribute, and Egyptian oversight in Canaan.", "They frame the city-state environment that forms background for Joshua and Judges without serving as a direct witness to either book.", "14th century BCE", "Regnal chronology of Amenhotep III and Akhenaten, script, and archive context", "Identification of particular cities and social groups is debated; the archive is not a biblical narrative.", "Vorderasiatisches Museum, Berlin; British Museum; other collections", "British Museum", "https://www.britishmuseum.org/collection/galleries/ancient-egypt-and-sudan", periods=["Broad / uncertain period"], dispute="interpretation_disputed"),
    _item("beni-hasan-asiatic-caravan", "beni-hasan", "Beni Hasan 'Asiatic' Caravan Painting", "Middle Kingdom tomb painting", "Middle Kingdom Egypt", "Egyptian visual context for Levantine migrants", "The scene gives a rare Egyptian image of a Levantine caravan entering Egypt with goods and animals.", "It should not be labeled an image of Jacob's family, Joseph, or the Israelites.", "A painted procession in the tomb of Khnumhotep II at Beni Hasan.", "Recorded in a provincial official's rock-cut tomb rather than an excavation layer.", "Wall painting showing people labeled Aamu, animals, textiles, and equipment.", "It documents Egyptian representation of a small Levantine group in a Middle Kingdom administrative setting.", "It offers careful comparative context for Genesis migration narratives, especially Genesis 46, without identifying the depicted people with biblical figures.", "c. 1890 BCE", "Tomb owner's date and Middle Kingdom artistic context", "The depiction and its Aamu label are clear; ethnic and historical identifications beyond the inscription are uncertain.", "Tomb 3, Beni Hasan", "Metropolitan Museum of Art", "https://www.metmuseum.org/art/collection/search/544858", periods=["Broad / uncertain period"], dispute="interpretation_disputed"),
    _item("shechem-middle-bronze", "shechem", "Middle Bronze Shechem Fortifications", "fortification and temple complex", "Middle Bronze Age", "highland urban context", "The massive defenses and cultic architecture show the scale of a major highland city.", "They cannot be assigned directly to Abraham, Jacob, or a named event in Genesis.", "Middle Bronze ramparts, gates, and a temple complex at Tell Balata.", "Successive expeditions exposed fortifications and public structures on the tell.", "Cyclopean-style masonry, earthen ramparts, gate architecture, and temple remains.", "The remains demonstrate urban organization and fortified settlement in central Canaan.", "They provide material context for Shechem in Genesis 12 and 33, where the place is named, without proving the narratives.", "c. 1900–1550 BCE", "Stratigraphy, ceramics, and architectural sequence", "The Middle Bronze urban phase is secure; links to specific patriarchal episodes are historical setting only.", "Tell Balata archaeological site", "UNESCO World Heritage Centre", "https://whc.unesco.org/en/tentativelists/5708/", periods=["Broad / uncertain period"], dispute="interpretation_disputed"),
    _item("avaris-excavations", "avaris", "Avaris / Tell el-Dab'a Excavations", "Delta settlement archaeology", "Middle Bronze to New Kingdom Egypt", "Egyptian-Levantine contact context", "The site's houses, burials, and material culture reveal long-term Levantine presence in the eastern Delta.", "It does not identify an Israelite population or determine an Exodus route or date.", "A multi-period settlement containing domestic areas, cemeteries, palatial phases, and imported material culture.", "Austrian excavations mapped a large settlement beneath later Ramesside activity.", "Mudbrick architecture, burials, ceramics, and administrative/elite installations.", "The evidence demonstrates varied Levantine-Egyptian contact and settlement in the Delta.", "It is comparative background for Exodus 1's Egyptian setting, not evidence for an Israelite sojourn.", "c. 1800–1500 BCE, with later New Kingdom phases", "Stratigraphy, ceramics, and Egyptian historical chronology", "The site sequence is well documented; equating particular groups at Avaris with biblical Israelites is not supported by the evidence.", "Tell el-Dab'a archaeological site", "Austrian Archaeological Institute", "https://www.oeaw.ac.at/oeai/research/egypt-and-levant/tell-el-daba", periods=["Broad / uncertain period"], dispute="interpretation_disputed"),
    _item("pi-rameses-qantir", "pi-rameses", "Pi-Ramesses / Qantir Archaeology", "Ramesside royal capital and workshops", "New Kingdom Egypt", "Egyptian imperial infrastructure", "The city preserves evidence for royal building, chariot production, and state-scale craft activity.", "Its name and location do not settle the historical geography or chronology of Exodus 1.", "The archaeological remains of a Ramesside Delta capital, much of it relocated by river changes and later reuse.", "Survey, geophysics, and excavation at Qantir identified palatial and industrial areas associated with Pi-Ramesses.", "Mudbrick buildings, workshop traces, and dispersed monumental stone elements.", "The site illuminates New Kingdom royal logistics and the eastern Delta landscape.", "It provides historical setting for the store-city name Ramesses in Exodus 1:11, while the textual and archaeological correlations remain debated.", "13th century BCE", "Ramesside inscriptions, settlement sequence, and geological study", "Pi-Ramesses is securely a Ramesside capital; connecting it to a particular Exodus chronology exceeds the site evidence.", "Qantir archaeological area; Roemer- und Pelizaeus-Museum research archive", "Roemer- und Pelizaeus-Museum", "https://www.rpmuseum.de/forschung/projekte/qantir-piramesse.html", periods=["Broad / uncertain period"], dispute="chronology_disputed"),
    _item("timnah-excavations", "timnah", "Timnah (Tel Batash) Excavations", "border-town settlement sequence", "Late Bronze and Iron Age", "Philistine-Judahite border context", "The sequence helps reconstruct life in the Shephelah, a contested zone between highlands and coast.", "The identification with biblical Timnah and correlations with Samson traditions are not equally secure in every period.", "A tell with Late Bronze, Iron Age, and later remains in the Sorek/Elah region.", "Excavations exposed domestic, industrial, and defensive remains across multiple phases.", "Mudbrick and stone architecture, installations, ceramics, and small finds.", "The material sequence documents a changing borderland landscape.", "It provides geographical and cultural context for Samson's movement to Timnah in Judges 14, not confirmation of the story's events.", "Late Bronze–Iron Age II", "Stratigraphy and ceramic chronology", "Several sites have been proposed for biblical Timnah; this identification is useful but should remain cautious.", "Tel Batash archaeological site", "Tel Aviv University", "https://english.tau.ac.il/news/timnah", periods=["Divided Kingdom"], dispute="identification_disputed", confidence="likely"),
    _item("ekron-excavations", "ekron", "Ekron (Tel Miqne) Excavations", "Philistine city and industrial complex", "Iron Age", "Philistine urban and economic context", "The city reveals Philistine urban development, cult, and later olive-oil production at exceptional scale.", "Excavations describe a city and its institutions; they do not verify each episode involving Philistine rulers in Samuel.", "A large Philistine city with domestic quarters, temples, fortifications, and industrial installations.", "Long-term excavations exposed Iron Age levels and a major late Iron Age olive-oil industrial zone.", "Stone and mudbrick architecture, cultic objects, storage facilities, and presses.", "Ekron is one of the best excavated sources for Philistine material culture and economy.", "It provides direct place context for 1 Samuel 5:10 and historical setting for Philistine society in Samuel.", "12th–7th centuries BCE", "Stratigraphy, ceramics, inscriptions, and Assyrian-era destruction evidence", "The site identification is secure; textual correlations should be limited to the named place and period context.", "Tel Miqne archaeological site", "Israel Antiquities Authority", "https://www.antiquities.org.il/", periods=["Divided Kingdom", "Assyrian period"]),
    _item("ekron-dedicatory-inscription", "ekron", "Ekron Royal Dedicatory Inscription", "Philistine royal building inscription", "Iron Age IIB", "Philistine royal and cultic context", "The inscription names a king of Ekron and a goddess in a temple context.", "It does not identify Goliath, the rulers in Samuel, or a biblical event.", "A Phoenician-style inscription from a temple complex at Ekron.", "Found in the late Iron Age temple area during Tel Miqne excavations.", "Limestone inscription naming Achish son of Padi and dedicating a sanctuary to Ptgyh.", "It is rare epigraphic evidence for Philistine royal patronage and religious practice.", "It contextualizes the Philistine city named in 1 Samuel 5:10 and the political world of 1 Samuel 27 without equating its king with every biblical Achish.", "7th century BCE", "Excavation context, script, and historical names", "The inscription's reading is well established; proposed equations with biblical characters are debated.", "Israel Museum, Jerusalem", "Israel Museum", "https://www.imj.org.il/en/collections/", periods=["Assyrian period"], dispute="interpretation_disputed"),
    _item("philistine-bichrome-pottery", "ekron", "Philistine Bichrome Pottery", "decorated ceramic tradition", "Iron Age I", "Philistine material culture", "The pottery is a recognizable marker of early Philistine cultural formation on the southern coast.", "Ceramic style indicates cultural interaction, not a simple ethnic label for every household or biblical individual.", "Decorated serving and storage vessels from Philistine sites, including Ekron.", "Recovered in excavated domestic, public, and funerary contexts at several coastal sites.", "Wheel-made vessels with red and black geometric, bird, and floral decoration.", "It shows adaptation of Aegean and Levantine ceramic traditions in early Iron Age Philistia.", "It provides cultural background for Philistine groups in Judges 13–16 and 1 Samuel 4, rather than a direct witness to those narratives.", "12th–11th centuries BCE", "Stratigraphy, ceramic typology, and regional distribution", "Interpretations of migration, ethnicity, and cultural change remain more complex than a single pottery style.", "Israel Museum and excavation collections", "Israel Museum", "https://www.imj.org.il/en/collections/", periods=["Divided Kingdom"], dispute="interpretation_disputed"),
    _item("gezer-calendar", "gezer", "Gezer Calendar", "early Hebrew agricultural inscription", "Iron Age IIA", "literacy and agricultural context", "The short inscription is important evidence for early alphabetic writing and the agricultural year in the highlands.", "Its precise function, date, and authorship remain discussed; it is not a biblical calendar.", "A small limestone tablet with an agricultural sequence in early Hebrew script.", "Found at Gezer in 1908 in a mixed archaeological context.", "A limestone plaque with eight short lines describing agricultural activities.", "It preserves a compact account of seasonal agricultural work and early alphabetic literacy.", "It gives cultural context for agricultural imagery and seasonal rhythms in texts such as 1 Kings 8:2, without serving as a direct textual witness.", "10th century BCE", "Palaeography and archaeological context", "The script and broad date are accepted, but the object’s exact provenance, purpose, and dating remain debated.", "Istanbul Archaeological Museums", "Israel Museum", "https://www.imj.org.il/en/collections/", periods=["Divided Kingdom"], dispute="interpretation_disputed"),
    _item("khirbet-qeiyafa-fortress", "khirbet-qeiyafa", "Khirbet Qeiyafa Fortified Site", "fortified urban settlement", "Iron Age IIA", "early Judahite/Shephelah context", "The planned settlement and fortifications make early Iron Age state formation in the Elah Valley tangible.", "Its ethnic identity, political affiliation, and relationship to Saul or David remain debated.", "A walled hilltop settlement with two gates, casemate fortification, houses, and cultic/administrative finds.", "Excavated from 2007 to 2013 after earlier survey identification.", "Stone casemate wall, monumental gates, dense domestic plan, and administrative artifacts.", "The site provides unusually well-preserved evidence for a short-lived fortified community in the Elah Valley.", "It frames the strategic landscape of 1 Samuel 17, set in the Valley of Elah, without identifying the site as a scene in the narrative.", "late 11th–early 10th century BCE", "Radiocarbon dates, ceramics, stratigraphy, and architecture", "Scholars disagree whether the site was Judahite, Israelite, Canaanite, or another polity and how it relates to biblical chronology.", "Khirbet Qeiyafa archaeological site", "Hebrew University of Jerusalem", "https://qeiyafa.huji.ac.il/", periods=["Divided Kingdom"], dispute="interpretation_disputed", confidence="likely"),
    _item("khirbet-qeiyafa-ostracon", "khirbet-qeiyafa", "Khirbet Qeiyafa Ostracon", "ink inscription on pottery", "Iron Age IIA", "early alphabetic literacy context", "The ostracon is evidence for writing practices in the Elah Valley at the start of the monarchy period.", "Its damaged text and language are disputed; it should not be used to claim a settled biblical institution or named person.", "A five-line ink inscription on a pottery sherd.", "Recovered in 2008 in an Iron Age IIA context within the fortified site.", "A ceramic sherd bearing a short, fragmentary inscription in early alphabetic script.", "It contributes evidence for scribal activity in a debated early Iron Age highland/lowland context.", "It offers comparative background for the literacy and administration assumed in 1 Samuel 17's early-monarchy setting, not a direct link to David.", "late 11th–early 10th century BCE", "Excavation context, palaeography, and radiocarbon sequence", "Proposed readings, language identification, and social implications remain actively contested.", "Israel Antiquities Authority collections", "Hebrew University of Jerusalem", "https://qeiyafa.huji.ac.il/", periods=["Divided Kingdom"], dispute="interpretation_disputed", confidence="likely"),
    _item("kuntillet-ajrud-inscriptions", "kuntillet-ajrud", "Kuntillet Ajrud Inscriptions", "Hebrew and Phoenician inscriptions with drawings", "Iron Age IIB", "Israelite/Judahite religion and writing context", "The inscriptions reveal vernacular religious language and scribal practice beyond the biblical corpus.", "Readings of the divine names, drawings, and implications for Israelite religion are disputed and must not be simplified.", "Inscriptions and drawings on pithoi and plaster from a desert station.", "Excavated in 1975–76 in rooms and courtyard areas at the site.", "Ink texts and drawings on large storage jars and plaster fragments.", "They provide rare evidence for Iron Age religious language, pilgrimage/travel, and inscriptional practice.", "They offer carefully qualified context for debates around worship in 1 Kings 12 and prophetic critique, rather than proof of a biblical character's beliefs.", "late 9th–early 8th century BCE", "Palaeography, pottery, and excavation context", "The inscriptions are secure; reconstructing theology, social setting, and named referents from fragmentary texts is contested.", "Israel Museum, Jerusalem", "Israel Museum", "https://www.imj.org.il/en/collections/", periods=["Divided Kingdom", "Assyrian period"], dispute="interpretation_disputed"),
    _item("tel-dan-cultic-complex", "tel-dan", "Tel Dan Cultic Complex", "Iron Age cultic architecture", "Iron Age II", "northern kingdom cultic context", "The complex preserves a built setting for public ritual and sacrifice in the northern kingdom period.", "Its identification with the specific sanctuary in 1 Kings 12 is plausible but not certain, and its phases require careful distinction.", "A multi-phase podium, altar area, and associated installations near Tel Dan's gate complex.", "Excavated in successive campaigns at the northern tell.", "Stone platforms, stairs, ash deposits, cultic installations, and later modifications.", "It is major archaeological evidence for Iron Age public cult architecture in the north.", "It gives historical setting for the Dan sanctuary in 1 Kings 12:28–30, while avoiding a claim that every exposed phase is Jeroboam's shrine.", "10th–8th centuries BCE", "Stratigraphy, architecture, ceramics, and associated finds", "The cultic function is widely accepted, but dates and correlation with biblical kings remain debated.", "Tel Dan National Park", "Israel Nature and Parks Authority", "https://en.parks.org.il/reserve-park/tel-dan-national-park/", periods=["Divided Kingdom", "Assyrian period"], dispute="interpretation_disputed"),
    _item("lachish-siege-ramp", "lachish", "Lachish Assyrian Siege Ramp", "siege earthwork", "Neo-Assyrian period", "Assyrian campaign warfare", "The ramp gives exceptionally concrete evidence for how an Assyrian army assaulted a fortified Judean city.", "Its link to Sennacherib's 701 BCE campaign is strong, but the ramp does not narrate every episode in Kings or Isaiah.", "A stone-and-earth ramp ascending toward Lachish's southwest corner with evidence for defenders' counter-ramp.", "Excavated and surveyed on the outside of the Level III city wall.", "Packed stones and earth forming an engineered assault approach against the city fortifications.", "It is among the clearest archaeological examples of Neo-Assyrian siege engineering in the Levant.", "It provides direct historical setting for 2 Kings 18:13–17 and Isaiah 36:1–2, where Lachish is central to Sennacherib's campaign.", "701 BCE", "Level III destruction context, Assyrian relief comparison, and campaign chronology", "The association with the 701 campaign is widely accepted; it must not be turned into proof of every outcome described in the biblical and Assyrian accounts.", "Tel Lachish National Park", "Israel Antiquities Authority", "https://www.antiquities.org.il/", periods=["Assyrian period"]),
    _item("lachish-destruction-level", "lachish", "Lachish Level III Destruction", "destruction layer and city remains", "Neo-Assyrian period", "late Judah destruction context", "The burned and ruined city level documents the devastating material impact of Assyrian imperial warfare.", "Destruction evidence establishes a violent episode, not the complete narrative or theological interpretation of 2 Kings 18–19.", "The Level III city, gate, and domestic areas destroyed in the late eighth century BCE.", "British, Israeli, and later excavations documented burned debris, weaponry, and collapsed architecture.", "Burned mudbrick and stone structures, destruction deposits, weapons, and damaged fortifications.", "The level provides an archaeological counterpart to the destruction of Lachish represented in Assyrian royal art.", "It complements the Lachish Reliefs and siege ramp in the 2 Kings 18 / Isaiah 36 cluster.", "701 BCE", "Stratigraphy, ceramics, destruction deposits, and Assyrian campaign chronology", "The destruction is securely linked to the Assyrian campaign; its evidence does not resolve differences between royal propaganda and biblical narrative.", "Tel Lachish National Park", "Israel Antiquities Authority", "https://www.antiquities.org.il/", periods=["Assyrian period"]),
    _item("silwan-tombs", "jerusalem-archaeology", "Silwan Iron Age Tombs", "rock-cut elite tombs", "Iron Age II", "Jerusalem burial and administration context", "The tombs reveal elite burial architecture and inscriptions on Jerusalem's eastern slope.", "Specific tomb-owner identifications, including the debated association of one tomb with a royal steward, remain uncertain.", "A group of rock-cut tombs in the Kidron Valley slope opposite the City of David.", "Documented in nineteenth- and twentieth-century surveys and later archaeological study.", "Monumental rock-cut chambers, benches, façades, and fragmentary Hebrew inscription evidence.", "They provide rare material evidence for late monarchic Jerusalem burial practice and elite status.", "They form cultural background for royal officials and burial language in Isaiah 22:15–16, not a secure identification of Shebna's tomb.", "8th–7th centuries BCE", "Architecture, inscriptions, and Iron Age Jerusalem context", "The tomb group is established; linking a damaged inscription and a specific tomb to biblical Shebna is disputed.", "Silwan / Kidron Valley, Jerusalem", "Israel Antiquities Authority", "https://www.antiquities.org.il/", periods=["Assyrian period", "Babylonian period"], dispute="identification_disputed", confidence="likely"),
    _item("jerusalem-babylonian-destruction", "jerusalem-archaeology", "Jerusalem Babylonian Destruction Evidence", "destruction deposits and urban remains", "late Iron Age II", "fall of Judah historical setting", "Burned debris, collapsed buildings, and arrowheads provide physical evidence for Jerusalem's violent end in the early sixth century BCE.", "Archaeology documents destruction and rebuilding phases; it does not independently narrate Jeremiah's speeches or every event of 586 BCE.", "Destruction deposits from several areas of late Iron Age Jerusalem, including the City of David and western hill.", "Excavations exposed burned structures, ash, pottery, and weaponry in stratified late Iron Age contexts.", "Collapsed stone and mudbrick architecture, ash deposits, vessels, bullae, and arrowheads.", "The evidence is consistent with major urban destruction at the end of the Judean monarchy.", "It provides historical setting for 2 Kings 25:8–10 and Jeremiah 39:1–8, which describe Babylonian destruction of Jerusalem.", "early 6th century BCE", "Stratigraphy, ceramics, inscriptions, and Babylonian historical chronology", "The destruction horizon is secure, while dating and interpreting individual contexts require attention to each excavation area.", "City of David and Jerusalem excavation collections", "Israel Antiquities Authority", "https://www.antiquities.org.il/", periods=["Babylonian period"]),
    _item("jehoiachin-ration-tablets", "babylon", "Jehoiachin Ration Tablets", "Neo-Babylonian administrative tablets", "Neo-Babylonian period", "exilic administration context", "The tablets preserve rations for 'Yaukin, king of Judah' and Judean associates in Babylonian administration.", "They attest a named Judean king in exile but do not narrate 2 Kings or establish the theological meaning of exile.", "Several cuneiform ration tablets from Neo-Babylonian Babylon.", "Recovered in Babylon and published among administrative tablets from the city.", "Small clay tablets listing oil rations in Akkadian cuneiform.", "They independently attest Jehoiachin's presence in Babylonian royal administration.", "They provide narrow historical context for 2 Kings 25:27–30 and Ezekiel 1:2, which place Jehoiachin in exile.", "c. 592 BCE", "Tablet dates, Akkadian names, and Neo-Babylonian administrative chronology", "The identification of Jehoiachin is widely accepted; the tablets provide only the limited information their administrative texts preserve.", "Vorderasiatisches Museum, Berlin", "Vorderasiatisches Museum", "https://www.smb.museum/en/museums-institutions/vorderasiatisches-museum/collection-research/collection/", periods=["Babylonian period"]),
    _item("al-yahudu-tablets", "babylon", "Al-Yahudu Tablets", "Neo-Babylonian and Persian administrative archive", "Neo-Babylonian to Persian period", "Judean exilic life context", "The documents preserve personal names, land, taxes, credit, and family life among Judeans in Babylonia.", "The archive is not a record of a single biblical community and cannot be made to speak for all exiles.", "A dispersed group of legal and administrative tablets referring to Al-Yahudu, 'Judah-town.'", "The tablets entered collections through the antiquities market; their ancient archive context is reconstructed from texts rather than excavated provenance.", "Clay cuneiform tablets recording contracts, taxes, agricultural obligations, and names.", "They are unusually rich evidence for the social and economic life of Judean deportee communities.", "They contextualize exilic life in Ezekiel 1:1–3 and Jeremiah 29 without identifying the biblical authors or recipients.", "6th–5th centuries BCE", "Dated legal formulas, script, and Neo-Babylonian/Persian chronology", "The texts are genuine and historically valuable, but their unexcavated modern provenance and limits of representativeness require caution.", "Various museum and private collections", "Cornell University Library", "https://exhibits.library.cornell.edu/alayahudu", periods=["Babylonian period", "Persian period"], dispute="provenance_disputed"),
    _item("yehud-coinage", "jerusalem-archaeology", "Yehud Coinage", "Persian-period provincial coins", "Persian period", "Persian Judah administration context", "The coins make the small province of Yehud and its economic practices visible in material form.", "Iconography and issuing authority are debated; a coin does not directly identify the people or events in Ezra-Nehemiah.", "Small silver coins bearing Yehud legends and varied symbols.", "Recovered from excavations and collections in Judah and neighboring regions.", "Tiny silver coins with paleo-Hebrew or Aramaic legends, motifs, and occasional personal names.", "They attest a monetized provincial economy and local administrative identity in the Persian period.", "They provide historical setting for the Persian-period community described in Ezra 1–6, not direct evidence for the edicts or rebuilding episodes.", "5th–4th centuries BCE", "Legends, typology, hoards, and archaeological contexts", "Many coins lack secure excavation contexts, and readings/attributions of types remain debated.", "Israel Museum and Israel Antiquities Authority collections", "Israel Museum", "https://www.imj.org.il/en/collections/", periods=["Persian period"], dispute="interpretation_disputed"),
    _item("jerusalem-mikvaot", "jerusalem-archaeology", "Jerusalem Ritual Baths (Mikva'ot)", "Second Temple water installations", "Second Temple period", "purity-practice context", "Stepped pools with plastered walls show the infrastructure of ritual immersion around late Second Temple Jerusalem.", "Not every stepped pool is a mikveh, and installations should not be mapped automatically onto a particular Gospel scene.", "Numerous stepped, plastered pools in Jerusalem and its approaches.", "Excavated in domestic, public, and pilgrimage-route contexts around the city.", "Rock-cut or built pools with steps, partitions, and waterproof plaster.", "They are important archaeological evidence for the centrality of purity practices and water management.", "They give material background for purification language and Jerusalem festival settings in John 2 and John 11, without explaining a particular ritual action.", "late 1st century BCE–1st century CE", "Architecture, plaster technology, associated ceramics, and stratigraphy", "Classification relies on form and context; individual installations can have more than one function.", "Jerusalem archaeological sites", "Israel Antiquities Authority", "https://www.antiquities.org.il/", periods=["Hellenistic period", "NT / Roman period"], dispute="interpretation_disputed"),
    _item("jewish-stone-vessels", "jerusalem-archaeology", "Jewish Stone Vessels", "chalkstone household vessels", "late Second Temple period", "purity and daily-life context", "The widespread use of chalkstone cups and jars is a tangible feature of Jewish domestic practice in the late Second Temple period.", "Their relationship to purity law is widely argued but should not be reduced to a universal rule for every user or household.", "Chalkstone cups, bowls, and large jars from Jerusalem, Galilee, and other Jewish settlement contexts.", "Found in stratified domestic, workshop, and refuse deposits; production workshops are known near Jerusalem.", "Lathe-turned and carved vessels made from local soft limestone/chalk.", "They document specialized craft production and a distinctive material practice in Jewish communities.", "They provide cultural setting for stone jars in John 2:6 and purification discussions in Mark 7:3–4 without proving the specific Cana vessels.", "1st century BCE–1st century CE", "Stratigraphy, typology, workshop evidence, and associated material culture", "The broad association with purity practice is strong, while the meaning and distribution of individual vessel types remain debated.", "Israel Museum and Israel Antiquities Authority collections", "Israel Museum", "https://www.imj.org.il/en/collections/", periods=["Hellenistic period", "NT / Roman period"], dispute="interpretation_disputed"),
    _item("qumran-settlement", "qumran", "Qumran Settlement Archaeology", "Second Temple settlement complex", "Second Temple period", "Dead Sea Scroll discovery context", "The settlement, its installations, and nearby caves provide physical provenance context for the Qumran scroll discoveries.", "The occupants' identity and the relationship between the settlement and every scroll cave remain debated.", "A settlement with water systems, workshops, communal rooms, and adjacent caves in the northwest Dead Sea region.", "Excavated principally by Roland de Vaux and later reexamined by several projects.", "Stone-built rooms, cisterns, channels, pottery facilities, and cemetery areas.", "It is essential archaeological context for the physical discovery environment of the Dead Sea Scrolls.", "It gives geographical and material setting for the desert-Judea world of John the Baptist in Mark 1:4–5, while the Scrolls' textual content remains in the manuscripts domain.", "2nd century BCE–1st century CE", "Stratigraphy, pottery, coins, architecture, and cave deposits", "There is no consensus on all aspects of the site's community, economy, or relation to the scroll corpus.", "Qumran National Park and Israel Antiquities Authority collections", "Israel Antiquities Authority", "https://www.antiquities.org.il/", periods=["Hellenistic period", "NT / Roman period"], dispute="interpretation_disputed"),
    _item("nazareth-archaeology", "nazareth", "Nazareth Early Roman-Period Archaeology", "village domestic and burial remains", "early Roman period", "Galilean village setting", "Domestic structures, storage features, and tombs give a small Galilean village a material profile.", "Archaeology cannot identify Jesus' family home or verify individual Gospel episodes.", "Scattered early Roman-period domestic and burial evidence beneath modern Nazareth.", "Rescue and research excavations have documented features in several parts of the modern city.", "Rock-cut pits, cisterns, domestic walls, agricultural terraces, and tombs.", "The remains support Nazareth's occupation as a modest village in the early Roman period.", "They provide direct place setting for Luke 4:16–24 and Mark 1:9, which name Nazareth, without assigning structures to Gospel characters.", "1st century BCE–1st century CE", "Ceramics, construction, tomb types, and stratigraphy", "The early Roman village is well supported, while its precise extent and particular structures remain limited by modern development.", "Nazareth archaeological areas", "Israel Antiquities Authority", "https://www.antiquities.org.il/", periods=["Hellenistic period", "NT / Roman period"]),
    _item("magdala-synagogue", "magdala", "Magdala First-Century Synagogue", "synagogue building and carved stone", "early Roman period", "Galilean synagogue context", "The excavated building is one of the few securely first-century synagogues in Galilee and includes the famous Magdala Stone.", "It is not named in the Gospels and should not be assigned to a specific visit by Jesus.", "A synagogue within the excavated lakeside town of Magdala, with a carved stone furnishing.", "Found during salvage excavations in 2009 before construction near Migdal.", "Benches along walls, mosaic floor, frescoed surfaces, columns, and a carved stone with menorah imagery.", "It provides unusually direct evidence for a first-century Galilean gathering space and its visual world.", "It gives cultural context for Jesus teaching in Galilean synagogues in Mark 1:21 and Mark 6:2, without claiming the building appears in those accounts.", "1st century CE", "Coins, ceramics, stratigraphy, and architectural context", "The date and synagogue identification are strong; interpretation of the Magdala Stone's imagery and function remains debated.", "Magdala archaeological site", "Israel Antiquities Authority", "https://www.antiquities.org.il/", periods=["NT / Roman period"], dispute="interpretation_disputed"),
    _item("bethsaida-identification", "bethsaida", "Bethsaida Identification Debate: et-Tell and el-Araj", "site-identification and settlement evidence", "Hellenistic to Roman period", "Gospel geography debate", "Excavations at two northern-Galilee candidates provide a concrete basis for assessing Bethsaida's location.", "Neither candidate should be presented as conclusively the Bethsaida of the Gospels.", "Two excavated candidate areas: et-Tell inland and el-Araj nearer the lake.", "Independent projects have exposed settlement, fishing, domestic, and public remains at the competing sites.", "Architecture, ceramics, coins, fishing equipment, and changing shoreline evidence.", "The debate shows how lake-level and settlement geography affect historical reconstruction.", "It directly concerns Bethsaida in Mark 8:22–26 and John 1:44, but BHF presents the competing evidence rather than selecting a winner.", "1st century BCE–1st century CE", "Stratigraphy, ceramics, coins, shoreline reconstruction, and historical geography", "Scholars remain divided over whether et-Tell, el-Araj, another location, or changing names best explain the evidence.", "et-Tell and el-Araj excavation areas", "Kinneret Institute for Galilean Archaeology", "https://www.kinneret.ac.il/en/kinneret-institute-for-galilean-archaeology/", periods=["Hellenistic period", "NT / Roman period"], dispute="identification_disputed", confidence="likely"),
    _item("galilee-fishing-boat", "galilee-boat-site", "First-Century Galilee Fishing Boat", "wooden fishing boat", "early Roman period", "Galilean daily-life context", "The preserved hull gives unusually direct evidence for the construction and scale of a working boat on the Sea of Galilee.", "It cannot be linked to Jesus, disciples, or a Gospel voyage.", "A waterlogged wooden hull preserved in lake sediments near Gennesaret.", "Discovered during a 1986 drought and excavated in a rapid rescue operation.", "A roughly 8.2-meter hull built from multiple wood species, repaired repeatedly in antiquity.", "It documents practical fishing and transport technology in the early Roman Galilee lake economy.", "It provides material setting for boat travel and fishing in Mark 4:35–41 and John 21:1–14 without identifying a biblical vessel.", "late 1st century BCE–1st century CE", "Radiocarbon dates, construction analysis, and associated ceramics", "The dating and general function are secure; popular associations with biblical figures are unsupported.", "Yigal Allon Centre, Kibbutz Ginosar", "Yigal Allon Centre", "https://yigal-allon-centre.org.il/", periods=["NT / Roman period"]),
    _item("corinth-excavations", "corinth", "Corinth Archaeological Site", "Roman colonial cityscape", "Roman imperial period", "Acts urban setting", "The forum, shops, fountains, temples, and streets show the civic environment of a major Roman colony.", "The site is direct context for a named city but does not locate every event or house mentioned in Acts and the letters.", "The excavated center of Roman Corinth, rebuilt as a colony after 44 BCE.", "American and Greek excavations have investigated the forum and surrounding city since the late nineteenth century.", "Paved forum, basilicas, shops, fountains, temples, inscriptions, and streets.", "It gives material context for law, trade, public speech, and urban religion in Roman Achaia.", "It supplies direct place context for Acts 18:1–17 and social setting for 1 Corinthians.", "1st century BCE–2nd century CE", "Architecture, inscriptions, coins, ceramics, and colonial history", "Urban identification is secure; matching particular excavated rooms to named New Testament individuals is usually speculative.", "Ancient Corinth Archaeological Site", "American School of Classical Studies at Athens", "https://www.ascsa.edu.gr/excavations/research/corinth", periods=["NT / Roman period"]),
    _item("corinth-bema", "corinth", "Corinth Bema and Forum Tribunal Area", "civic tribunal platform", "Roman imperial period", "Acts legal setting", "The raised platform in the forum illustrates the kind of public judicial and civic space in which Acts situates Gallio's hearing.", "The visible bema should not be claimed as the exact spot or unchanged structure of Paul's appearance.", "A prominent platform and associated civic architecture in the Roman forum of Corinth.", "Exposed in the excavation of the forum and studied in relation to its successive Roman phases.", "Stone platform with steps and surrounding paved public space.", "It demonstrates the public, civic character of legal proceedings in a Roman colonial forum.", "It gives direct urban context for Acts 18:12–17, while the Gallio inscription remains the primary chronological evidence.", "1st–2nd centuries CE", "Forum stratigraphy, architecture, and inscriptions", "The forum function is clear; the exact architectural phase present at Paul's hearing cannot be asserted from the present remains alone.", "Ancient Corinth Archaeological Site", "American School of Classical Studies at Athens", "https://www.ascsa.edu.gr/excavations/research/corinth", periods=["NT / Roman period"], dispute="interpretation_disputed"),
    _item("erastus-inscription", "corinth", "Erastus Pavement Inscription", "Latin civic inscription", "Roman imperial period", "Corinthian civic-administration context", "The inscription names an Erastus who financed paving as an aedile, illuminating elite benefaction in Corinth.", "The named official cannot be securely identified with the Erastus in Romans 16:23.", "A fragmentary Latin inscription embedded in paving near the Corinth theater area.", "Found in the twentieth-century excavation of Roman Corinth.", "Large pavement blocks preserving the name Erastus and an aedile title.", "It offers material evidence for municipal office and benefaction in the city.", "It gives social context for Romans 16:23 and Acts 18's Corinth setting, but BHF keeps the personal identification explicitly open.", "1st–2nd centuries CE", "Letter forms, paving context, and municipal title", "The inscription is real and the civic title clear; dating and identification with the Pauline associate are disputed.", "Ancient Corinth Archaeological Museum/site", "American School of Classical Studies at Athens", "https://www.ascsa.edu.gr/excavations/research/corinth", periods=["NT / Roman period"], dispute="identification_disputed", confidence="likely"),
    _item("ephesus-theater", "ephesus", "Ephesus Great Theater", "Roman theater and civic assembly space", "Roman imperial period", "Acts public-assembly context", "The theater illustrates the monumental civic setting of public gathering in Ephesus.", "It cannot prove the exact crowd, speech, or sequence described in Acts 19.", "A large theater on the slope of Mount Pion, expanded through Hellenistic and Roman phases.", "Excavated and restored through long-running Austrian archaeological work.", "A stone cavea, stage building remains, inscriptions, and connections to major streets.", "The monument documents the scale and organization of public spectacle and assembly in Roman Ephesus.", "It provides direct city context for Acts 19:29–41, which places a civic disturbance in an Ephesian theater.", "Hellenistic foundations; major Roman phases", "Architecture, inscriptions, and excavation sequence", "The theater's identity is certain; connecting a particular architectural detail to the Acts episode goes beyond the evidence.", "Ephesus archaeological site", "Austrian Archaeological Institute", "https://www.oeaw.ac.at/oeai/research/ephesos", periods=["Hellenistic period", "NT / Roman period"]),
    _item("temple-artemis-ephesus", "ephesus", "Temple of Artemis at Ephesus", "sanctuary and cult landscape", "Archaic to Roman period", "Artemis cult context", "The sanctuary was a major regional religious and economic institution, central to Ephesian civic identity.", "The remains do not prove the particulars of Demetrius's speech or the size of the Acts 19 crowd.", "The site of the Artemision, with successive temple phases and associated votive/cultic material.", "Excavated by British and Austrian teams from the nineteenth century onward.", "Foundations, column fragments, architectural elements, and votive deposits from a long-lived sanctuary.", "It documents the physical and economic importance of Artemis worship in Ephesus.", "It gives direct historical setting for Acts 19:24–28, where artisans invoke Artemis and her temple.", "6th century BCE–Roman period", "Architectural sequence, inscriptions, literary sources, and excavated deposits", "The sanctuary's importance is secure; archaeological remains cannot independently verify the narrated riot.", "Ephesus Archaeological Museum and Artemision site", "British Museum", "https://www.britishmuseum.org/collection/galleries/greece-and-rome", periods=["Hellenistic period", "NT / Roman period"]),
    _item("philippi-forum", "philippi", "Philippi Roman Forum", "colonial civic center", "Roman imperial period", "Acts Macedonian urban setting", "The forum, basilica, and street system provide the civic setting of a Roman colony in Macedonia.", "The traditional 'prison' identification is not included here as a demonstrated location of Acts 16.", "The central public area of Roman Philippi, built over earlier Hellenistic phases.", "Systematic excavations exposed the forum, administrative buildings, streets, and inscriptions.", "Paved square, basilicas, shops, monuments, and road infrastructure.", "It makes visible the Roman-colonial institutions and public space behind the narrative.", "It provides direct city context for Acts 16:12–40, especially the magistrates and public proceedings, without identifying a specific prison cell.", "1st century BCE–3rd century CE", "Architecture, inscriptions, coins, and colonial history", "The city context is firm; popular localizations of individual Acts scenes remain unproven.", "Philippi archaeological site", "Greek Ministry of Culture", "https://odysseus.culture.gr/h/3/eh351.jsp?obj_id=18848", periods=["NT / Roman period"]),
    _item("smyrna-roman-city", "smyrna", "Smyrna Roman City Archaeology", "agora, inscriptions, and urban remains", "Roman imperial period", "Revelation city context", "The agora and inscriptions show a prosperous city marked by civic benefaction and Roman imperial culture.", "The archaeology does not determine the meaning of Revelation's imagery or reconstruct the specific church addressed.", "Roman public architecture and inscriptions in ancient Smyrna/Izmir.", "Excavations and conservation work have documented the agora and associated structures.", "Arcades, graffiti, inscriptions, water systems, and civic monuments.", "They provide material evidence for dense urban life and civic institutions in Roman Asia.", "It supplies city context for Revelation 2:8–11, whose addressee is in Smyrna.", "1st–3rd centuries CE", "Architecture, inscriptions, and stratigraphy", "The city identification is certain; connections between individual monuments and Revelation's language remain interpretive.", "Smyrna Agora archaeological site", "İzmir Archaeology Museum", "https://muze.gov.tr/muze-detay?SectionId=IZM01&DistId=MRK", periods=["NT / Roman period"]),
    _item("pergamum-imperial-cult", "pergamum", "Pergamum Imperial Cult and Acropolis", "sanctuaries and civic-monumental landscape", "Hellenistic to Roman period", "Revelation imperial-cult context", "Pergamum's acropolis preserves major sanctuaries and early provincial imperial-cult evidence.", "No single structure should be declared 'Satan's throne'; Revelation's phrase is interpretive rather than an archaeological label.", "A monumental acropolis with temples, altar remains, theater, and later imperial-cult architecture.", "Excavated primarily by German archaeological projects from the nineteenth century onward.", "Terraced sanctuaries, monumental architecture, inscriptions, and sculpture.", "The city materially demonstrates the political, religious, and visual landscape of Roman Asia.", "It provides historical setting for Revelation 2:12–17 while avoiding a forced identification of the passage's imagery.", "2nd century BCE–2nd century CE", "Architecture, inscriptions, sculpture, and excavation sequence", "Pergamum's cult landscape is well documented; proposed one-to-one symbols for Revelation remain disputed.", "Pergamon Museum, Berlin; Bergama site", "German Archaeological Institute", "https://www.dainst.org/en/research/projects/nosl/2225", periods=["Hellenistic period", "NT / Roman period"], dispute="interpretation_disputed"),
    _item("thyatira-trade-and-inscriptions", "thyatira", "Thyatira Trade Guild and Inscription Context", "Roman urban inscriptions and industry", "Roman imperial period", "Revelation economic context", "Inscriptions and material remains illuminate a commercial city known for crafts and associations.", "They do not identify Lydia of Acts 16 or establish a direct causal reading of Revelation's critique.", "Roman inscriptions, architectural remains, and industrial traces from ancient Thyatira.", "Recovered through surveys, excavations, and museum collections in and around modern Akhisar.", "Greek and Latin inscriptions, building fragments, coins, and evidence for local production.", "They provide context for civic associations, work, and urban religion in Roman Asia.", "It gives city and economic context for Revelation 2:18–29 and offers cautious background for Lydia's Thyatiran origin in Acts 16:14.", "1st–3rd centuries CE", "Inscriptions, coins, architecture, and regional survey", "The city and its economic activity are clear, while detailed reconstructions of trade guilds and Revelation's referents remain debated.", "Akhisar Archaeological Museum collections", "Türkiye Ministry of Culture and Tourism", "https://whc.unesco.org/en/tentativelists/6243/", periods=["NT / Roman period"], dispute="interpretation_disputed"),
    _item("sardis-synagogue", "sardis", "Sardis Synagogue", "monumental Roman synagogue", "Roman imperial period", "Jewish diaspora context in Asia", "The large synagogue documents a visible, wealthy Jewish community within a major Roman city.", "It was built centuries after Revelation and cannot be used as a snapshot of the first-century church.", "A monumental synagogue incorporated into a bath-gymnasium complex at Sardis.", "Excavated by the Harvard-Cornell Sardis Expedition in the twentieth century.", "Marble revetment, mosaic floors, Greek and Hebrew inscriptions, and a large assembly hall.", "It is key archaeological evidence for Jewish communal life in Roman Asia Minor.", "It supplies later Roman Jewish context for Sardis in Revelation 3:1–6 without assigning the building to the first-century congregation.", "3rd–5th centuries CE", "Architecture, inscriptions, coins, and stratigraphy", "The synagogue is secure; its chronological distance from Revelation must remain visible.", "Sardis archaeological site", "Harvard Art Museums / Sardis Expedition", "https://sardisexpedition.org/en/essays/about-synagogue", periods=["NT / Roman period"]),
    _item("philadelphia-city-archaeology", "philadelphia-lydia", "Philadelphia (Lydia) City Archaeology", "Roman and later urban remains", "Roman imperial period", "Revelation city context", "Scattered inscriptions, walls, and urban remains establish the physical setting of an inland Lydian city.", "Modern development and later rebuilding limit what can be said about the first-century Christian community.", "Roman-period remains and later fortifications in ancient Philadelphia/Alaşehir.", "Recorded by survey, rescue work, and standing-monument documentation rather than a single large excavation.", "Architectural fragments, inscriptions, streets, and later defensive walls.", "The evidence situates Philadelphia within the connected urban network of Roman Asia.", "It provides direct city context for Revelation 3:7–13, while its metaphors should not be reduced to a single surviving monument.", "1st–3rd centuries CE", "Inscriptions, architecture, and regional historical geography", "The city location is secure, but first-century remains are comparatively limited and later structures dominate the visible landscape.", "Alaşehir archaeological areas", "Türkiye Ministry of Culture and Tourism", "https://whc.unesco.org/en/tentativelists/6243/", periods=["NT / Roman period"], confidence="likely"),
    _item("laodicea-water-system", "laodicea", "Laodicea Water System and City Archaeology", "Roman aqueduct and urban infrastructure", "Roman imperial period", "Revelation water and wealth context", "Aqueducts, pipes, and city remains show the engineering and urban prosperity of Laodicea.", "The evidence can illuminate local conditions but cannot settle every interpretation of 'lukewarm' in Revelation.", "Water channels, pipework, public buildings, streets, and residential remains at Laodicea.", "Ongoing excavations have documented major Roman urban sectors and water installations.", "Stone and ceramic pipes, water distribution features, colonnaded streets, theaters, and civic buildings.", "They demonstrate the city's dependence on managed water supply and its substantial urban infrastructure.", "They give material setting for Revelation 3:14–22, while BHF presents the water-metaphor connection as contextual rather than certain.", "1st–3rd centuries CE", "Architecture, hydraulic study, inscriptions, and stratigraphy", "Laodicea's water infrastructure is clear; the precise rhetorical background of Revelation's temperature imagery remains debated.", "Laodicea archaeological site", "Laodicea Excavations", "https://laodikeia.pau.edu.tr/", periods=["NT / Roman period"], dispute="interpretation_disputed"),
]


ARCHAEOLOGY_SCRIPTURE_LINKS: list[dict[str, Any]] = [
    {"id": "asl-mari-genesis-1", "item_id": "mari-tablets", "book": "Genesis", "chapter": 12, "verse_start": 1, "verse_end": 9, "relationship_type": "comparative_context", "notes": "Middle Bronze Near Eastern travel, administration, and religion context; not evidence for Abraham."},
    {"id": "asl-ugarit-kings-1", "item_id": "ugaritic-baal-cycle", "book": "1 Kings", "chapter": 18, "verse_start": 20, "verse_end": 40, "relationship_type": "comparative_context", "notes": "Comparative West Semitic religious vocabulary and mythology; not an Israelite text."},
    {"id": "asl-amarna-joshua-1", "item_id": "amarna-letters", "book": "Joshua", "chapter": 10, "verse_start": 1, "verse_end": 5, "relationship_type": "historical_context", "notes": "Late Bronze Canaanite city-state political context only."},
    {"id": "asl-beni-hasan-genesis-1", "item_id": "beni-hasan-asiatic-caravan", "book": "Genesis", "chapter": 46, "verse_start": 1, "verse_end": 7, "relationship_type": "comparative_context", "notes": "Egyptian visual context for Levantine migration; not Jacob's family."},
    {"id": "asl-shechem-genesis-1", "item_id": "shechem-middle-bronze", "book": "Genesis", "chapter": 12, "verse_start": 6, "verse_end": 7, "relationship_type": "historical_setting", "notes": "Named-place and Middle Bronze urban context."},
    {"id": "asl-avaris-exodus-1", "item_id": "avaris-excavations", "book": "Exodus", "chapter": 1, "verse_start": 1, "verse_end": 14, "relationship_type": "comparative_context", "notes": "Eastern Delta Egyptian-Levantine settlement context; not Israelite identification."},
    {"id": "asl-pi-rameses-exodus-1", "item_id": "pi-rameses-qantir", "book": "Exodus", "chapter": 1, "verse_start": 11, "verse_end": 11, "relationship_type": "historical_setting", "notes": "Ramesside Delta capital context; Exodus chronology remains debated."},
    {"id": "asl-timnah-judges-1", "item_id": "timnah-excavations", "book": "Judges", "chapter": 14, "verse_start": 1, "verse_end": 5, "relationship_type": "possible_association", "notes": "Candidate Timnah regional context; site identification is disputed."},
    {"id": "asl-ekron-samuel-1", "item_id": "ekron-excavations", "book": "1 Samuel", "chapter": 5, "verse_start": 10, "verse_end": 12, "relationship_type": "direct_context", "notes": "Ekron is explicitly named in the narrative."},
    {"id": "asl-ekron-inscription-samuel-1", "item_id": "ekron-dedicatory-inscription", "book": "1 Samuel", "chapter": 27, "verse_start": 1, "verse_end": 12, "relationship_type": "historical_context", "notes": "Philistine royal-context evidence; not identification of biblical Achish."},
    {"id": "asl-philistine-pottery-judges-1", "item_id": "philistine-bichrome-pottery", "book": "Judges", "chapter": 13, "verse_start": 1, "verse_end": 5, "relationship_type": "cultural_context", "notes": "Early Philistine material culture context."},
    {"id": "asl-gezer-calendar-kings-1", "item_id": "gezer-calendar", "book": "1 Kings", "chapter": 8, "verse_start": 2, "verse_end": 2, "relationship_type": "cultural_context", "notes": "Agricultural-year and early writing context only."},
    {"id": "asl-qeiyafa-fortress-samuel-1", "item_id": "khirbet-qeiyafa-fortress", "book": "1 Samuel", "chapter": 17, "verse_start": 1, "verse_end": 3, "relationship_type": "historical_setting", "notes": "Elah Valley fortified-site context; interpretation remains disputed."},
    {"id": "asl-qeiyafa-ostracon-samuel-1", "item_id": "khirbet-qeiyafa-ostracon", "book": "1 Samuel", "chapter": 17, "verse_start": 1, "verse_end": 3, "relationship_type": "comparative_context", "notes": "Early alphabetic literacy context; text does not mention David."},
    {"id": "asl-kuntillet-kings-1", "item_id": "kuntillet-ajrud-inscriptions", "book": "1 Kings", "chapter": 12, "verse_start": 25, "verse_end": 33, "relationship_type": "cultural_context", "notes": "Iron Age religious-inscription context; specific implications are debated."},
    {"id": "asl-tel-dan-cultic-kings-1", "item_id": "tel-dan-cultic-complex", "book": "1 Kings", "chapter": 12, "verse_start": 28, "verse_end": 30, "relationship_type": "possible_association", "notes": "Dan cultic architecture; correlation of phases with Jeroboam remains debated."},
    {"id": "asl-lachish-ramp-kings-1", "item_id": "lachish-siege-ramp", "book": "2 Kings", "chapter": 18, "verse_start": 13, "verse_end": 17, "relationship_type": "historical_context", "notes": "Assyrian siege engineering at Lachish in the 701 BCE campaign."},
    {"id": "asl-lachish-destruction-isaiah-1", "item_id": "lachish-destruction-level", "book": "Isaiah", "chapter": 36, "verse_start": 1, "verse_end": 2, "relationship_type": "historical_context", "notes": "Lachish destruction context for Sennacherib's campaign."},
    {"id": "asl-lachish-destruction-kings-1", "item_id": "lachish-destruction-level", "book": "2 Kings", "chapter": 18, "verse_start": 13, "verse_end": 17, "relationship_type": "historical_context", "notes": "Lachish Level III destruction in the 701 BCE campaign context."},
    {"id": "asl-silwan-isaiah-1", "item_id": "silwan-tombs", "book": "Isaiah", "chapter": 22, "verse_start": 15, "verse_end": 16, "relationship_type": "disputed_association", "notes": "Elite tomb and possible steward-inscription context; Shebna link is disputed."},
    {"id": "asl-jerusalem-destruction-kings-1", "item_id": "jerusalem-babylonian-destruction", "book": "2 Kings", "chapter": 25, "verse_start": 8, "verse_end": 10, "relationship_type": "historical_context", "notes": "Late Iron Age Jerusalem destruction context."},
    {"id": "asl-jerusalem-destruction-jeremiah-1", "item_id": "jerusalem-babylonian-destruction", "book": "Jeremiah", "chapter": 39, "verse_start": 1, "verse_end": 8, "relationship_type": "historical_context", "notes": "Babylonian destruction context, not a narrative transcript."},
    {"id": "asl-jehoiachin-kings-1", "item_id": "jehoiachin-ration-tablets", "book": "2 Kings", "chapter": 25, "verse_start": 27, "verse_end": 30, "relationship_type": "historical_context", "notes": "Administrative tablets name Jehoiachin in Babylonian ration lists."},
    {"id": "asl-al-yahudu-ezekiel-1", "item_id": "al-yahudu-tablets", "book": "Ezekiel", "chapter": 1, "verse_start": 1, "verse_end": 3, "relationship_type": "historical_setting", "notes": "Judean exilic-life context in Babylonia; not Ezekiel's own archive."},
    {"id": "asl-yehud-ezra-1", "item_id": "yehud-coinage", "book": "Ezra", "chapter": 1, "verse_start": 1, "verse_end": 4, "relationship_type": "historical_setting", "notes": "Persian Yehud provincial context, not evidence for Cyrus's decree."},
    {"id": "asl-mikvaot-john-1", "item_id": "jerusalem-mikvaot", "book": "John", "chapter": 2, "verse_start": 1, "verse_end": 11, "relationship_type": "cultural_context", "notes": "Purification-water infrastructure context; not the Cana jars."},
    {"id": "asl-stone-vessels-john-1", "item_id": "jewish-stone-vessels", "book": "John", "chapter": 2, "verse_start": 6, "verse_end": 6, "relationship_type": "cultural_context", "notes": "Late Second Temple stone-vessel context for purification jars."},
    {"id": "asl-qumran-settlement-mark-1", "item_id": "qumran-settlement", "book": "Mark", "chapter": 1, "verse_start": 4, "verse_end": 5, "relationship_type": "historical_setting", "notes": "Judean desert material setting; no direct link to John the Baptist."},
    {"id": "asl-nazareth-luke-1", "item_id": "nazareth-archaeology", "book": "Luke", "chapter": 4, "verse_start": 16, "verse_end": 24, "relationship_type": "direct_context", "notes": "Nazareth is explicitly named in the narrative."},
    {"id": "asl-magdala-mark-1", "item_id": "magdala-synagogue", "book": "Mark", "chapter": 1, "verse_start": 21, "verse_end": 28, "relationship_type": "cultural_context", "notes": "First-century Galilean synagogue setting; not a claimed Gospel location."},
    {"id": "asl-bethsaida-mark-1", "item_id": "bethsaida-identification", "book": "Mark", "chapter": 8, "verse_start": 22, "verse_end": 26, "relationship_type": "disputed_association", "notes": "Competing archaeological candidates for Bethsaida."},
    {"id": "asl-galilee-boat-john-1", "item_id": "galilee-fishing-boat", "book": "John", "chapter": 21, "verse_start": 1, "verse_end": 14, "relationship_type": "cultural_context", "notes": "Early Roman fishing-boat context, not a biblical vessel."},
    {"id": "asl-corinth-acts-1", "item_id": "corinth-excavations", "book": "Acts", "chapter": 18, "verse_start": 1, "verse_end": 17, "relationship_type": "direct_context", "notes": "Corinth is the named urban setting."},
    {"id": "asl-corinth-bema-acts-1", "item_id": "corinth-bema", "book": "Acts", "chapter": 18, "verse_start": 12, "verse_end": 17, "relationship_type": "historical_setting", "notes": "Forum tribunal setting; exact location of hearing is not asserted."},
    {"id": "asl-erastus-romans-1", "item_id": "erastus-inscription", "book": "Romans", "chapter": 16, "verse_start": 23, "verse_end": 23, "relationship_type": "disputed_association", "notes": "Civic Erastus inscription; identification with Romans is disputed."},
    {"id": "asl-ephesus-theater-acts-1", "item_id": "ephesus-theater", "book": "Acts", "chapter": 19, "verse_start": 29, "verse_end": 41, "relationship_type": "direct_context", "notes": "Ephesian theater is the narrative's stated assembly setting."},
    {"id": "asl-artemis-acts-1", "item_id": "temple-artemis-ephesus", "book": "Acts", "chapter": 19, "verse_start": 24, "verse_end": 28, "relationship_type": "historical_context", "notes": "Artemis sanctuary and cult context for the episode."},
    {"id": "asl-philippi-acts-1", "item_id": "philippi-forum", "book": "Acts", "chapter": 16, "verse_start": 12, "verse_end": 40, "relationship_type": "direct_context", "notes": "Philippi is the named colonial-city setting."},
    {"id": "asl-smyrna-revelation-1", "item_id": "smyrna-roman-city", "book": "Revelation", "chapter": 2, "verse_start": 8, "verse_end": 11, "relationship_type": "direct_context", "notes": "Smyrna is the named city of the address."},
    {"id": "asl-pergamum-revelation-1", "item_id": "pergamum-imperial-cult", "book": "Revelation", "chapter": 2, "verse_start": 12, "verse_end": 17, "relationship_type": "historical_setting", "notes": "Pergamum cult landscape; no single monument is assigned to the imagery."},
    {"id": "asl-thyatira-revelation-1", "item_id": "thyatira-trade-and-inscriptions", "book": "Revelation", "chapter": 2, "verse_start": 18, "verse_end": 29, "relationship_type": "direct_context", "notes": "Thyatira is the named city of the address."},
    {"id": "asl-sardis-revelation-1", "item_id": "sardis-synagogue", "book": "Revelation", "chapter": 3, "verse_start": 1, "verse_end": 6, "relationship_type": "historical_setting", "notes": "Sardis city context; synagogue is later than Revelation."},
    {"id": "asl-philadelphia-revelation-1", "item_id": "philadelphia-city-archaeology", "book": "Revelation", "chapter": 3, "verse_start": 7, "verse_end": 13, "relationship_type": "direct_context", "notes": "Philadelphia is the named city of the address."},
    {"id": "asl-laodicea-revelation-1", "item_id": "laodicea-water-system", "book": "Revelation", "chapter": 3, "verse_start": 14, "verse_end": 22, "relationship_type": "historical_setting", "notes": "Water and city context; rhetorical connection remains debated."},
]


# Exact Commons files were reviewed separately.  These two records establish
# the expansion's media workflow without treating an image search result as an
# automatically approved asset; the remaining entries remain text-first until
# their own file-and-rights reviews are committed.
ARCHAEOLOGY_MEDIA: list[dict[str, Any]] = [
    {"id": "wm-magdala-synagogue-2025", "archaeology_item_id": "magdala-synagogue", "title": "Ancient synagogue in Magdala", "caption": "Excavated remains of the ancient synagogue at Magdala.", "source_url": "https://commons.wikimedia.org/wiki/File:140368_ancient_synagogue_in_magdala_PikiWiki_Israel.jpg", "image_url": "https://commons.wikimedia.org/wiki/Special:FilePath/140368%20ancient%20synagogue%20in%20magdala%20PikiWiki%20Israel.jpg", "creator": "Michal Freiman", "institution": "PikiWiki Israel", "license_id": "CC BY 2.5", "license_url": "https://creativecommons.org/licenses/by/2.5/", "rights_status": "cc_by", "can_redistribute": True, "can_cache": True, "can_modify": True, "source_record_id": "File:140368 ancient synagogue in magdala PikiWiki Israel.jpg"},
    {"id": "wm-sardis-synagogue-courtyard", "archaeology_item_id": "sardis-synagogue", "title": "Sardis Synagogue courtyard", "caption": "Courtyard remains of the Sardis synagogue.", "source_url": "https://commons.wikimedia.org/wiki/File:Sardis_Synagogue_courtyard.JPG", "image_url": "https://commons.wikimedia.org/wiki/Special:FilePath/Sardis%20Synagogue%20courtyard.JPG", "creator": "AtilimGunesBaydin", "institution": "Wikimedia Commons", "license_id": "Public domain", "rights_status": "public_domain", "can_redistribute": True, "can_cache": True, "can_modify": True, "source_record_id": "File:Sardis Synagogue courtyard.JPG"},
]
