#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Compose BHF modules into a single prompt.

Usage:
    python tools/compose.py --modules genre.epistle,book.romans
    python tools/compose.py --profile standard
    python tools/compose.py --profile standard --write   # write profiles/standard.md

Dependencies declared in each module's `requires` are resolved automatically and
ordered (core first). Output is a single Markdown prompt suitable for any model's
system prompt / custom instructions / Modelfile.

Profiles are defined in profiles/profiles.yml as named lists of module ids.
"""

from __future__ import annotations

import argparse
from pathlib import Path

import yaml

from bhf_lib import estimate_tokens, load_modules, resolve

REPO_ROOT = Path(__file__).resolve().parent.parent
FRAMEWORK_DIR = REPO_ROOT / "framework"
PROFILES_FILE = REPO_ROOT / "profiles" / "profiles.yml"
CORE_FRAMEWORK_ID = "core.core-framework"
CORE_FRAMEWORK_IMPLIED_MODULES = ["core.intertextuality"]

HEADER = """# Biblical Hermeneutics Framework — Composed Prompt

You are assisting with biblical interpretation. Follow the method below. It tells
you *how* to interpret responsibly; it does not tell you *what* to conclude.
Never present a single denomination's doctrine as the answer. Where scholarship
is divided, present the major views and label your confidence.

> Generated by tools/compose.py — do not edit by hand. Profile: {profile}.
> Modules ({count}, ~{tokens} tokens): {ids}
"""


def load_profiles() -> dict[str, list[str]]:
    if not PROFILES_FILE.exists():
        return {}
    data = yaml.safe_load(PROFILES_FILE.read_text(encoding="utf-8")) or {}
    profiles = (data.get("profiles") or {}).items()
    return {name: list(spec.get("modules", [])) for name, spec in profiles}


def compose(selected: list[str], profile_label: str) -> tuple[str, int]:
    modules = load_modules(FRAMEWORK_DIR)
    ordered = resolve(modules, selected)
    ordered_ids = {mod.id for mod in ordered}
    if CORE_FRAMEWORK_ID in ordered_ids:
        implied = [mid for mid in CORE_FRAMEWORK_IMPLIED_MODULES
                   if mid not in ordered_ids]
        if implied:
            ordered = resolve(modules, selected + implied)
    parts: list[str] = []
    for mod in ordered:
        parts.append(
            f"<!-- {mod.id} v{mod.version} -->\n"
            f"# {mod.title}\n{mod.body.strip()}\n")
    body = "\n---\n\n".join(parts)
    total = sum(estimate_tokens(m.body) for m in ordered)
    header = HEADER.format(
        profile=profile_label,
        count=len(ordered),
        tokens=total,
        ids=", ".join(m.id for m in ordered),
    )
    return header + "\n" + body, total


def main() -> int:
    ap = argparse.ArgumentParser(description="Compose BHF modules into one prompt.")
    group = ap.add_mutually_exclusive_group(required=True)
    group.add_argument("--modules", help="comma-separated module ids")
    group.add_argument("--profile", help="named profile from profiles/profiles.yml")
    ap.add_argument("--write", action="store_true",
                    help="write to profiles/<profile>.md instead of stdout")
    args = ap.parse_args()

    if args.profile:
        profiles = load_profiles()
        if args.profile not in profiles:
            known = ", ".join(profiles) or "(none)"
            print(f"unknown profile '{args.profile}'. Known: {known}")
            return 1
        selected = profiles[args.profile]
        label = args.profile
    else:
        selected = [m.strip() for m in args.modules.split(",") if m.strip()]
        label = "custom"

    try:
        output, total = compose(selected, label)
    except KeyError as exc:
        print(f"error: unknown module {exc}")
        return 1
    except ValueError as exc:
        print(f"error: {exc}")
        return 1

    if args.write and args.profile:
        out_path = REPO_ROOT / "profiles" / f"{args.profile}.md"
        out_path.write_text(output, encoding="utf-8")
        print(f"wrote {out_path.relative_to(REPO_ROOT)} (~{total} tokens)")
    else:
        print(output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
